const EMPTY_STRING = "";

const TASK_REMINDER_ALARM_NAME = "TASK_REMINDER_ALARM";
const TASK_REMINDER_TODO = "TASK_REMINDER_TODO";

const CONTEXT_MENU_CREATE_TASK_ID = "CONTEXT_MENU_CREATE_TASK";

export default {
  EMPTY_STRING,
  TASK_REMINDER_ALARM_NAME,
  CONTEXT_MENU_CREATE_TASK_ID,
  TASK_REMINDER_TODO,
};
